# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_process', '0004_auto_20171011_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=4096, verbose_name='Опис курсу')),
                ('visible', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_process.Profile')),
                ('visible_for_groups', models.ManyToManyField(to='edu_process.Group')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва заняття')),
                ('short_description', models.TextField(max_length=512, verbose_name='Короткий опис заняття')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Lesson')),
            ],
            options={
                'verbose_name': 'Навчальний файл',
                'verbose_name_plural': 'Навчальні файли',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Опис модулю')),
                ('visible', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модулі',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Module'),
        ),
    ]
