# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0004_auto_20171011_1731'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_for_all', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='course',
            name='visible_for_groups',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='qwerty', max_length=128, verbose_name='Назва курсу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Назва модулю'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва заняття'),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='courselayout',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course'),
        ),
        migrations.AddField(
            model_name='courselayout',
            name='visible_for_groups',
            field=models.ManyToManyField(to='edu_process.Group'),
        ),
    ]
