# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0005_auto_20171024_1418'),
        ('teacher', '0002_auto_20171012_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фотографія')),
                ('content', models.TextField(max_length=8192, verbose_name='Контент')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_process.Profile')),
            ],
            options={
                'verbose_name': 'Публікація',
                'verbose_name_plural': 'Публікації',
            },
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file',
            field=models.FileField(upload_to=teacher.models.lesson_file_upload_path, verbose_name='Файл'),
        ),
    ]
