# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0007_temporaryuser_profile'),
        ('teacher', '0003_auto_20171024_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=48, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=512, verbose_name='Нотатка')),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_process.Profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Lesson')),
            ],
        ),
    ]
