# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_calendarnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarnote',
            options={'verbose_name': 'Календарний запис', 'verbose_name_plural': 'Календарні записи'},
        ),
    ]
