# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20171101_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='draft',
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='-', max_length=4096, verbose_name='Опис модулю'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(default='-', max_length=128, verbose_name='Назва модулю'),
            preserve_default=False,
        ),
    ]
