# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20171120_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselayout',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courselayout',
            name='visible_for_groups',
        ),
        migrations.DeleteModel(
            name='CourseLayout',
        ),
    ]
