# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20180324_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='photo',
        ),
        migrations.AddField(
            model_name='publication',
            name='markdown',
            field=models.BooleanField(default=True, verbose_name='Markdown'),
        ),
    ]
