# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0014_auto_20180220_1251'),
        ('teacher', '0011_auto_20180401_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='subscribed_courses', to='edu_process.Profile'),
        ),
    ]
