# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20180418_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, to='teacher.Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', to='edu_process.Profile'),
        ),
    ]
