# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_auto_20180418_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
    ]
