# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20180418_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=teacher.models.course_photo_path, verbose_name='Фото курсу'),
        ),
    ]
