# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0002_auto_20171011_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu_process.Group'),
        ),
    ]
