# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edu_process.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu_process', '0004_auto_20171011_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, verbose_name='Тимчасовий пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=edu_process.models.profile_photo_path, verbose_name='Фото'),
        ),
    ]
