# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0006_remove_temporaryuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_user', to='edu_process.Profile'),
        ),
    ]
