# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20171121_1055'),
        ('edu_process', '0007_temporaryuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Course'),
        ),
    ]
