# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0008_group_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, to='teacher.Course'),
        ),
    ]
