# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
