# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0013_auto_20180220_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',)},
        ),
    ]
