# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_process', '0015_remove_profile_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група студентів', 'verbose_name_plural': 'Групи студентів'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',), 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.DeleteModel(
            name='TemporaryUser',
        ),
    ]
